image: alpine:latest #luongnguyen/oyente

before_script:
 - apk add --no-cache nodejs nodejs-npm git python g++ make
 - npm install -g yarn
 - yarn

stages:
 - build
 - test
 - deploy
 - release
 - publish

build:
 stage: build
 script:
   - yarn build
   - yarn lint
   #- for f in ./contracts/*.sol; do python /oyente/oyente/oyente.py -s $f; done
 artifacts:
   paths:
     - build

test:
 stage: test
 script:
   - yarn testrpc &
   - yarn test

deploy to dev:
 environment: dev
 stage: deploy
 image: docker:latest
 services:
   - docker:dind
 script:
   - node scripts/waitForEthSyncDev.js
   - yarn deploy:dev
   - git config --global user.email "m@element36.io"
   - git config --global user.name "mb-element36"
   - git push https://mb-element36:${GITLAB_AUTH_TOKEN}@gitlab.com/cash36/contracts.git
 only:
   - develop

release dev contracts:
  environment: dev
  stage: release
  script:
    - npm install -g semver
    - git config --global user.email "m@element36.io"
    - git config --global user.name "mb-element36"
    - LAST_VERSION=$(npm --registry http://167.99.243.81:4873/ view cash36-contracts version)
    - NEW_VERSION=$(semver -i $LAST_VERSION)
    - git tag -a $NEW_VERSION-alpha -m "Version for dev"
    - git push https://mb-element36:${GITLAB_AUTH_TOKEN}@gitlab.com/cash36/contracts.git --tags
  only:
    - develop

publish dev contracts:
  environment: dev
  stage: publish
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  only:
    - develop

deploy to test:
 environment: test
 stage: deploy
 image: docker:latest
 services:
   - docker:dind
 script:
   - node scripts/waitForEthSyncTest.js
   - ./node_modules/.bin/truffle migrate --reset --compile-all --network test
   - git config --global user.email "m@element36.io"
   - git config --global user.name "mb-element36"
   - git push https://mb-element36:${GITLAB_AUTH_TOKEN}@gitlab.com/cash36/contracts.git
 only:
   - master

release test contracts:
  environment: test
  stage: release
  script:
    - npm install -g semver
    - git config --global user.email "m@element36.io"
    - git config --global user.name "mb-element36"
    - LAST_VERSION=$(npm --registry http://167.99.243.81:4873/ view cash36-contracts version)
    - NEW_VERSION=$(semver -i $LAST_VERSION)
    - git tag -d $NEW_VERSION-alpha
    - git push --delete https://mb-element36:${GITLAB_AUTH_TOKEN}@gitlab.com/cash36/contracts.git $NEW_VERSION-alpha
    - npm install -g semantic-release-gitlab
    - semantic-release-gitlab
  only:
    - master

publish test contracts:
  environment: test
  stage: publish
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  only:
    - master