image: alpine:latest #luongnguyen/oyente

before_script:
 - apk add --no-cache nodejs nodejs-npm git python g++ make curl
 - npm install -g yarn
 - yarn

stages:
 - build
 - test
 - deploy
 - release
 - publish
 - build_dependents

build:
 stage: build
 script:
   - yarn build
   - yarn lint
   #- for f in ./contracts/*.sol; do python /oyente/oyente/oyente.py -s $f; done
 only:
   - develop

test:
 stage: test
 script:
   - yarn testrpc &
   - yarn test
 only:
   - develop

release:dev:
  environment: dev
  stage: release
  script:
    - npm install -g semver
    - git config --global user.email "m@element36.io"
    - git config --global user.name "mb-element36"
    - LAST_VERSION=$(npm --registry http://167.99.243.81:4873/ view cash36-contracts version)
    - NEW_VERSION=$(semver -i $LAST_VERSION)
    - git tag -a $NEW_VERSION-alpha -m "Version for dev"
    - git push https://mb-element36:${GITLAB_AUTH_TOKEN}@gitlab.com/cash36/contracts.git --tags
  only:
    - develop

publish:dev:
  environment: dev
  stage: publish
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  only:
    - develop

build_dev_backend:
  environment: dev
  stage: build_dependents
  script:
    - "curl -X POST -F token=89b63b9b65e497bc6fb528e079c7b3 -F ref=develop https://gitlab.com/api/v4/projects/6256736/trigger/pipeline"
  only:
    - develop

deploy:test:
 environment: test
 stage: deploy
 image: docker:latest
 services:
   - docker:dind
 script:
   - node scripts/waitForEthSyncTest.js
   - ./node_modules/.bin/truffle migrate --network test
   - ./node_modules/.bin/truffle networks
   - git config --global user.email "m@element36.io"
   - git config --global user.name "mb-element36"
   - 'git add .'
   - 'git commit -m "ci: push contracts after test deploy"'
   - 'git push https://mb-element36:${GITLAB_AUTH_TOKEN}@gitlab.com/cash36/contracts.git HEAD:master'
 artifacts:
   paths:
     - build/
 when: manual
 only:
   - master

release:test:
  environment: test
  stage: release
  script:
    - git config --global user.email "m@element36.io"
    - git config --global user.name "mb-element36"
    - npm install -g semantic-release-gitlab
    - semantic-release-gitlab
  dependencies:
    - deploy:test
  retry: 1
  when: manual
  allow_failure: false
  only:
    - master

publish:test:
  environment: test
  stage: publish
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  when: manual
  allow_failure: false
  only:
    - master

build_test_backend:
  environment: test
  stage: build_dependents
  script:
    - "curl -X POST -F token=89b63b9b65e497bc6fb528e079c7b3 -F ref=master https://gitlab.com/api/v4/projects/6256736/trigger/pipeline"
  when: manual
  allow_failure: false
  only:
    - master
