image: ubuntu:16.04 #luongnguyen/oyente

stages:
  # - build
  # - test
  # #- deploy
  # - release
  - publish

before_script:
  - apt-get update && apt-get install -y git python g++ make curl
  - curl -sL https://deb.nodesource.com/setup_10.x | bash
  - apt-get install -y nodejs
  - npm install -g yarn

# build:
#   stage: build
#   tags:
#     - dokcer
#   script:
#     - yarn
#     - yarn build
#     - yarn lint
#     #- for f in ./contracts/*.sol; do python /oyente/oyente/oyente.py -s $f; done
#   except:
#     - tags

# test:
#   stage: test
#   tags:
#     - dokcer
#   script:
#     - yarn
#     - yarn testrpc &
#     - yarn test
#   except:
#     - tags

# release:
#   stage: release
#   tags:
#     - dokcer
#   script:
#     - git config --global user.email "w@element36.io"
#     - git config --global user.name "walter.strametz"
#     - npm i -g @hutson/semantic-delivery-gitlab
#     - semantic-delivery-gitlab --token $GITLAB_AUTH_TOKEN
#     - npm install -g npm-publish-git-tag
#   retry: 1
#   allow_failure: false
#   only:
    - master

publish:
  stage: publish
  tags:
    - dokcer
  script:
    - git config --global user.email "w@element36.io"
    - git config --global user.name "walter.strametz"
    - echo "@element36-io:registry=https://npm.pkg.github.com" > ~/.npmrc
    - echo "registry=https://npm.pkg.github.com/element36-io" >> ~/.npmrc
    - echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN"  >> ~/.npmrc
    - cat ~/.npmrc
    - npm i -g @hutson/npm-deploy-git-tag
    # uses NPM_TOKEN from gitlab
    - npm-deploy-git-tag  --access private
  allow_failure: false
  #when: manual
  only:
    - master

#deploy:
#  stage: deploy
#  image: docker:latest
#  services:
#    - docker:dind
#  tags:
#    - dokcer
#  before_script:
#    - apk add --no-cache nodejs nodejs-npm git python g++ make curl
#    - npm install -g yarn
#    - yarn
#  script:
#    - node scripts/waitForEthSyncTest.js
#    - echo "{\"privKey\":\"${PRIVATE_KEY}\"}" > keys.json
#    - ./node_modules/.bin/truffle migrate --network test
#    - ./node_modules/.bin/truffle networks
#  artifacts:
#    paths:
#      - build/
#  only:
#    - maste