image: alpine:latest #luongnguyen/oyente

before_script:
 - apk add --no-cache nodejs nodejs-npm git python g++ make curl
 - npm install -g yarn
 - yarn

stages:
 - build
 - test
 - deploy
 - release
 - publish

build:
 stage: build
 script:
   - yarn build
   - yarn lint
   #- for f in ./contracts/*.sol; do python /oyente/oyente/oyente.py -s $f; done

test:
 stage: test
 script:
   - yarn testrpc &
   - yarn test

deploy:
 stage: deploy
 image: docker:latest
 services:
   - docker:dind
 script:
   - node scripts/waitForEthSyncTest.js
   - ./node_modules/.bin/truffle migrate --network test
   - ./node_modules/.bin/truffle networks
 artifacts:
   paths:
     - build/
 #when: manual
 only:
   - master

release:
  stage: release
  script:
    - git config --global user.email "m@element36.io"
    - git config --global user.name "mb-element36"
    - npm install -g semantic-release-gitlab
    - semantic-release-gitlab
  dependencies:
    - deploy:test
  retry: 1
  #when: manual
  allow_failure: false
  only:
    - master

publish:
  stage: publish
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  #when: manual
  allow_failure: false
  only:
    - master
