image: alpine:latest #luongnguyen/oyente

before_script:
 - apk add --no-cache nodejs nodejs-npm git python g++ make
 - npm install -g yarn
 - yarn

stages:
 - build
 - test
 - deploy
 - release
 - publish

build:
 stage: build
 script:
   - yarn build
   - yarn lint
   #- for f in ./contracts/*.sol; do python /oyente/oyente/oyente.py -s $f; done
 artifacts:
   paths:
     - build

test:
 stage: test
 script:
   - yarn testrpc &
   - yarn test
 artifacts:
   paths:
     - build

deploy to dev:
 environment: dev
 stage: deploy
 image: docker:latest
 services:
   - docker:dind
 script:
   - node scripts/waitForEthSyncDev.js
   - yarn deploy:dev
 artifacts:
   paths:
     - build
 only:
   - develop

release dev contracts:
  environment: dev
  stage: release
  script:
    - LAST_VERSION=$(npm --registry http://167.99.243.81:4873/ view cash36-contracts version)
    - git tag -a $LAST_VERSION-alpha -m "Version for dev"
    - git push origin --tags
  artifacts:
    paths:
      - build
  only:
    - develop

publish dev contracts:
  environment: dev
  stage: publish
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  artifacts:
    paths:
      - build
  only:
    - develop

deploy to test:
 environment: test
 stage: deploy
 image: docker:latest
 services:
   - docker:dind
 script:
   - node scripts/waitForEthSyncTest.js
   - ./node_modules/.bin/truffle migrate --reset --compile-all --network test
 artifacts:
   paths:
     - build
 only:
   - master

release test contracts:
  environment: test
  stage: release
  script:
    - npm install -g semantic-release-gitlab
    - semantic-release-gitlab
  artifacts:
    paths:
      - build
  only:
    - master

publish test contracts:
  environment: test
  stage: publish
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  artifacts:
    paths:
      - build
  only:
    - tags