image: alpine:latest #luongnguyen/oyente

before_script:
 - apk add --no-cache nodejs nodejs-npm git python g++ make
 - npm install -g yarn
 - yarn

stages:
 - build
 - test
 - deploy
 - release
 - publish

build:
 stage: build
 script:
   - yarn build
   - yarn lint
   #- for f in ./contracts/*.sol; do python /oyente/oyente/oyente.py -s $f; done
 artifacts:
   paths:
     - build

test:
 stage: test
 script:
   - yarn testrpc &
   - yarn test
 artifacts:
   paths:
     - build

deploy:
 stage: deploy
 environment: dev
 image: docker:latest
 services:
   - docker:dind
 script:
   #- docker run -v $(pwd):/app ethereum/client-go --datadir /app/geth/data init /app/geth/genesis.json
   #- docker run -d -p 8666:8666 -v $(pwd):/app ethereum/client-go --datadir /app/geth/data --fast --networkid 10 --rpc --unlock 0x8c5f7c9940e3d612703edbe8dfac8eb080709f3f --password ${GETH_PASSWORD} --rpcaddr "0.0.0.0" --verbosity 5
   - node scripts/waitForEthSync.js
   #- ./node_modules/.bin/truffle migrate --network local_dev
   - yarn deploy:dev
 artifacts:
   paths:
     - build
 only:
   - develop

release:
  stage: release
  environment: dev
  script:
    - npm install -g semantic-release-gitlab
    - semantic-release-gitlab
  artifacts:
    paths:
      - build
  only:
    - develop

publish:
  stage: publish
  environment: dev
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  artifacts:
    paths:
      - build
  only:
    - develop

deploy:
 stage: deploy
 environment: test
 image: docker:latest
 services:
   - docker:dind
 script:
   #- docker run -v $(pwd):/app ethereum/client-go --datadir /app/geth/data init /app/geth/genesis.json
   #- docker run -d -p 8666:8666 -v $(pwd):/app ethereum/client-go --datadir /app/geth/data --fast --networkid 10 --rpc --unlock 0x8c5f7c9940e3d612703edbe8dfac8eb080709f3f --password ${GETH_PASSWORD} --rpcaddr "0.0.0.0" --verbosity 5
   - node scripts/waitForEthSync.js
   #- ./node_modules/.bin/truffle migrate --network local_dev
   - yarn deploy:test
 artifacts:
   paths:
     - build
 only:
   - master

release:
  stage: release
  environment: test
  script:
    - npm install -g semantic-release-gitlab
    - semantic-release-gitlab
  artifacts:
    paths:
      - build
  only:
    - master

publish:
  stage: publish
  environment: test
  script:
    - npm install -g npm-publish-git-tag
    - echo "registry=http://167.99.243.81:4873/" > ~/.npmrc
    - echo "//167.99.243.81:4873/:_authToken='${NPM_TOKEN}'" > ~/.npmrc
    - npm-publish-git-tag --access public
  artifacts:
    paths:
      - build
  only:
    - master